{% set name = "vectormath" %}
{% set version = "0.2.0" %}
{% set sha256 = "80142d4c8d6110ba152df8447d8761eaa4c5459244138eb64718666340eefa4a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy >=1.7

test:
  imports:
    - vectormath

about:
  home: http://github.com/aranzgeo/vectormath
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Vector math utilities for Python built on NumPy'

  description: |
    The vectormath package provides a fast, simple library of vector math
    utilities by leveraging NumPy. This allows explicit
    geometric constructs to be created without redefining the underlying
    array math.
  doc_url: http://vectormath.readthedocs.io/
  dev_url: https://github.com/aranzgeo/vectormath

extra:
  recipe-maintainers:
    - fwkoch
