{% set name = "vectormath" %}
{% set version = "0.2.1" %}
{% set sha256 = "18afad14d1614c3b880e764a7a5d5928fd5140617803630a6ca45680c597c8f6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy >=1.7

test:
  imports:
    - vectormath

about:
  home: http://github.com/aranzgeo/vectormath
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Vector math utilities for Python built on NumPy'

  description: |
    The vectormath package provides a fast, simple library of vector math
    utilities by leveraging NumPy. This allows explicit
    geometric constructs to be created without redefining the underlying
    array math.
  doc_url: http://vectormath.readthedocs.io/
  dev_url: https://github.com/aranzgeo/vectormath

extra:
  recipe-maintainers:
    - fwkoch
