travis:
  secure:
    BINSTAR_TOKEN: oqI1Ra6xqaHyLa+8qNWbzBdb7BRxUbiIpHv90pSLXbr5F0t0RGfXlv3pUb+X9MbEmmpu/lMnny3Az/ZObX37kZpMYCXYhnli2gl91FfXmnAWkMYNTwKUqphn0/EQi1BX/oUmUTbP7RBWVzN7tQ6irDkeXUikLRw+UX4/5DPguSh0kIyJaos9DnWYh3MHyJ2ftjuZa1JPOaDdxotT6D8jEfPv5DvfaSJLnWTTtm28IV/dEdysciWaqUDIENsI5qlZsbNmG7IWh8RAmFVXv8BqbJxKjVQxHecURDxbgZhBklR8XN84636ZGLRuboZMtCTmtLnjwFPUzzCrNrPWFm3WCrsuCXKBE5itAX5D433OLhQl+Ckmpd8o+baXxvSkJZGAb3rXelnnY9mJxJlB8RZCiyx1ZBgluMY4VgKwZMdIGmVHr+IhDDBdXFHatowcaMmBf36gRarJ2OldP8maKSYOJdzCpHBR43EeyePp5G0ht0dcWl4sYmViYAHGa9Gm8SDFuFH9/1OTIqwA/5zd9472LC0wFzbC28t8sWObvmORq6rZzQLaMaS/lVfgIoRWaAWGd9IpkfEeulvdLZ4S6b02H6gjhOIBD4NRkg2faOPANMIFdONqPBpWbPg7BVg8sAVcXz652bFxzt4H2VGO+hgNvU9bOJ3VsTlaJvF5uufYe1o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
