travis:
  secure:
    BINSTAR_TOKEN: qqO+mcZKkrq5aBPR4D0AGmZZk4Hvt4Ib9RafB0BIHs4jPG0tInaEWA76FzwE1tx8TTxLE/jBVYBYBDIDw8DM2IGYxLy5RhbJBy4szMZyMC1mAWcjYjCVL1vvITKyCDEE1iG8YAfZbGpNlV/nxL8DqCH7CA/2he0VtS5mRsCal5tE6U3DRtZGXnV0V//lO8myOntplWoOM8hdq+hetbr+d6VNXe6JWfMGQ3TRsGqWe1rH66BtnIK3ofPqgzaElNMTQ2JRM1LFXcrfRUxNUweKj3+1nOGoRwP0XHcLSTG7/UX25DZ+eKeZsfF0aK1NNbTeYAyckajanccSRR06i1EqohnQCwO4cRWrLdrKUbET05owhj0R1FiNrroFT+b6yYLtgnkQUnwC+88ZNcqO3E61ICVKNUN6Ux4fiLKx6qqbOxj1xKmaakEVmgaqRrmStsx+05jnR0VoIkoQwmZ4YZl4NYINUvJ6/AQHCDESg/GmSoiY0Qh1tllbEdHmFX7e0NkRpoMsLHbzO+s0h+dIQGcEWIsLmw6EKMfyfgEXyfI+bZBkNy9JGHfqDvsn7hcItN5YSVsHyTH9zLZXZH7vIyNTlid+QAbIN4Jfbfvd7Nx+7fGmHerOngyz4tiAw7LG3/bUhoy2qonOhu0itzQAXo7wpiXHG2Z3S3VFubu9arCdQQc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
